obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.4, -0.3], [0.2, -0.3], [0.2, 0.3], [-0.4, 0.3]]
inflation_radius: 0.55
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
